#!/bin/bash

#==============================================================================
# Arch R - Generate Panel DTBO Overlays
#==============================================================================
# Generates DTBO overlay files for ALL panel variants:
#   - R36S originals (Panel 0-5) from decompiled DTS in kernel/dts/R36S-DTB/DTS/
#   - R36S clones (Clone Panel 1-10, R36 Max, RX6S) from compiled DTBs
#     in kernel/dts/R36S-Clones-DTB/
#
# These DTBOs are applied by U-Boot via boot.ini (panel auto-detect system).
# Base DTB has Panel 4-V22 hardcoded as default (works without overlay).
#==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DTS_DIR="$PROJECT_DIR/kernel/dts/R36S-DTB/DTS"
CLONES_DIR="$PROJECT_DIR/kernel/dts/R36S-Clones-DTB"
OUTPUT_DIR="$PROJECT_DIR/output/panels"

# Panel target path in our DTS
PANEL_PATH="/dsi@ff450000/panel@0"
TIMING_PATH="/dsi@ff450000/panel@0/display-timings/60Hz"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
log() { echo -e "${GREEN}[PANEL]${NC} $1"; }
warn() { echo -e "${YELLOW}[PANEL] WARNING:${NC} $1"; }
error() { echo -e "${RED}[PANEL] ERROR:${NC} $1"; exit 1; }

# Check for dtc
if ! command -v dtc &>/dev/null; then
    error "dtc (device-tree-compiler) not found. Install with: sudo apt install device-tree-compiler"
fi

mkdir -p "$OUTPUT_DIR"

#------------------------------------------------------------------------------
# Panel definitions: number, DTS file, clock, hfp, hsync, hbp, vfp, vsync, vbp,
#                    pixclk, reset_delay, prepare_delay, init_delay, enable_delay,
#                    width_mm, height_mm
#------------------------------------------------------------------------------

declare -A PANEL_DTS=(
    [0]="Panel0.dts"
    [1]="Panel1.dts"
    [2]="Panel2.dts"
    [3]="Panel3.dts"
    [4]="Panel4-V22.dts"
    [5]="Panel5.dts"
)

declare -A PANEL_CLOCK=(
    [0]=50000000  [1]=29163840  [2]=29163840
    [3]=29163840  [4]=58000000  [5]=40000000
)

declare -A PANEL_HFP=(
    [0]=450  [1]=80   [2]=46  [3]=46  [4]=300  [5]=120
)
declare -A PANEL_HSYNC=(
    [0]=46   [1]=20   [2]=2   [3]=2   [4]=200  [5]=120
)
declare -A PANEL_HBP=(
    [0]=450  [1]=80   [2]=44  [3]=44  [4]=300  [5]=120
)
declare -A PANEL_VFP=(
    [0]=17   [1]=20   [2]=16  [3]=16  [4]=17   [5]=17
)
declare -A PANEL_VSYNC=(
    [0]=5    [1]=4    [2]=2   [3]=2   [4]=5    [5]=5
)
declare -A PANEL_VBP=(
    [0]=13   [1]=12   [2]=14  [3]=14  [4]=13   [5]=13
)
declare -A PANEL_PIXCLK=(
    [0]=1  [1]=1  [2]=1  [3]=1  [4]=1  [5]=0
)
declare -A PANEL_RESET_DELAY=(
    [0]=1    [1]=150  [2]=150  [3]=150  [4]=150  [5]=50
)
declare -A PANEL_PREPARE_DELAY=(
    [0]=2    [1]=20   [2]=20   [3]=20   [4]=20   [5]=100
)
declare -A PANEL_ENABLE_DELAY=(
    [0]=120  [1]=120  [2]=120  [3]=120  [4]=120  [5]=200
)
declare -A PANEL_WIDTH=(
    [0]=52  [1]=52  [2]=52  [3]=52  [4]=52  [5]=71
)
declare -A PANEL_HEIGHT=(
    [0]=70  [1]=70  [2]=70  [3]=70  [4]=70  [5]=71
)

#------------------------------------------------------------------------------
# Extract panel-init-sequence from decompiled DTS
#------------------------------------------------------------------------------
extract_init_sequence() {
    local dts_file="$1"

    if [ ! -f "$dts_file" ]; then
        echo ""
        return
    fi

    # The init sequence is in byte-array format: panel-init-sequence = [hex hex hex ...];
    # It may span multiple lines (but in these files it's on one line)
    grep "panel-init-sequence" "$dts_file" | \
        sed 's/.*panel-init-sequence = \[//; s/\];.*//' | \
        tr -s ' ' | sed 's/^ //; s/ $//'
}

#------------------------------------------------------------------------------
# Generate .dtso overlay for a panel
#------------------------------------------------------------------------------
generate_dtso() {
    local panel_num="$1"
    local init_seq="$2"
    local dtso_file="$OUTPUT_DIR/panel${panel_num}.dtso"

    local clock="${PANEL_CLOCK[$panel_num]}"
    local hfp="${PANEL_HFP[$panel_num]}"
    local hsync="${PANEL_HSYNC[$panel_num]}"
    local hbp="${PANEL_HBP[$panel_num]}"
    local vfp="${PANEL_VFP[$panel_num]}"
    local vsync="${PANEL_VSYNC[$panel_num]}"
    local vbp="${PANEL_VBP[$panel_num]}"
    local pixclk="${PANEL_PIXCLK[$panel_num]}"
    local reset_delay="${PANEL_RESET_DELAY[$panel_num]}"
    local prepare_delay="${PANEL_PREPARE_DELAY[$panel_num]}"
    local enable_delay="${PANEL_ENABLE_DELAY[$panel_num]}"
    local width="${PANEL_WIDTH[$panel_num]}"
    local height="${PANEL_HEIGHT[$panel_num]}"

    cat > "$dtso_file" << DTSO_EOF
/dts-v1/;
/plugin/;

/* Arch R - Panel ${panel_num} MIPI DSI Overlay */
/* Auto-generated by generate-panel-dtbos.sh */

/ {
	fragment@0 {
		target-path = "${PANEL_PATH}";
		__overlay__ {
			prepare-delay-ms = <${prepare_delay}>;
			reset-delay-ms = <${reset_delay}>;
			init-delay-ms = <20>;
			enable-delay-ms = <${enable_delay}>;
			disable-delay-ms = <50>;
			unprepare-delay-ms = <20>;
			width-mm = <${width}>;
			height-mm = <${height}>;

			panel-init-sequence = [
				${init_seq}
			];

			panel-exit-sequence = [
				05 14 01 28
				05 0a 01 10
			];
		};
	};

	fragment@1 {
		target-path = "${TIMING_PATH}";
		__overlay__ {
			clock-frequency = <${clock}>;
			hactive = <640>;
			vactive = <480>;
			hfront-porch = <${hfp}>;
			hsync-len = <${hsync}>;
			hback-porch = <${hbp}>;
			vfront-porch = <${vfp}>;
			vsync-len = <${vsync}>;
			vback-porch = <${vbp}>;
			hsync-active = <0>;
			vsync-active = <0>;
			de-active = <0>;
			pixelclk-active = <${pixclk}>;
		};
	};
};
DTSO_EOF

    echo "$dtso_file"
}

#------------------------------------------------------------------------------
# Main
#------------------------------------------------------------------------------
log "=== Generating Panel DTBO Overlays ==="
log "Source: $DTS_DIR"
log "Output: $OUTPUT_DIR"
log ""

GENERATED=0
FAILED=0

for panel_num in 0 1 2 3 4 5; do
    dts_file="$DTS_DIR/${PANEL_DTS[$panel_num]}"
    log "Panel ${panel_num}: ${PANEL_DTS[$panel_num]}"

    # Extract init sequence
    init_seq=$(extract_init_sequence "$dts_file")
    if [ -z "$init_seq" ]; then
        warn "  Could not extract init-sequence from $dts_file"
        FAILED=$((FAILED + 1))
        continue
    fi

    seq_bytes=$(echo "$init_seq" | wc -w)
    log "  Init sequence: ${seq_bytes} bytes"
    log "  Clock: ${PANEL_CLOCK[$panel_num]} Hz"
    log "  Timings: ${PANEL_HFP[$panel_num]}/${PANEL_HSYNC[$panel_num]}/${PANEL_HBP[$panel_num]} ${PANEL_VFP[$panel_num]}/${PANEL_VSYNC[$panel_num]}/${PANEL_VBP[$panel_num]}"

    # Generate .dtso
    dtso_file=$(generate_dtso "$panel_num" "$init_seq")

    # Compile to .dtbo
    dtbo_file="$OUTPUT_DIR/panel${panel_num}.dtbo"
    if dtc -I dts -O dtb -@ -o "$dtbo_file" "$dtso_file" 2>/dev/null; then
        dtbo_size=$(stat -c%s "$dtbo_file")
        log "  Compiled: panel${panel_num}.dtbo (${dtbo_size} bytes)"
        GENERATED=$((GENERATED + 1))
    else
        warn "  Failed to compile panel${panel_num}.dtso"
        FAILED=$((FAILED + 1))
    fi
done

#------------------------------------------------------------------------------
# Clone Panel Definitions (from R36S-Clones-DTB compiled DTBs)
#------------------------------------------------------------------------------
# Clone panels are full compiled DTBs — we decompile with dtc to extract
# the panel-init-sequence. 5 unique types across 12 clone panels:
#   Type A (Clone 1,2,5,8): ST7703, 30MHz, hfp=150/hsync=50/hbp=150
#   Type B (Clone 3,4,6,9,RX6S): NV3051D, 30MHz, hfp=46/hsync=2/hbp=44
#   Type C (Clone 7): JD9365DA, 30MHz, hfp=188/hsync=20/hbp=186
#   Type D (Clone 10): ST7703 variant, 30MHz, hfp=120/hsync=120/hbp=120
#   Type E (R36 Max): ST7703 720x720, 50MHz, hfp=140/hsync=80/hbp=140
#------------------------------------------------------------------------------

# Clone panel DTB file mapping
declare -A CLONE_DTB=(
    ["Clone Panel 1"]="Panel 1/rf3536k4ka.dtb"
    ["Clone Panel 2"]="Panel 2/rf3536k4ka.dtb"
    ["Clone Panel 3"]="Panel 3/rf3536k4ka.dtb"
    ["Clone Panel 4"]="Panel 4/rf3536k4ka.dtb"
    ["Clone Panel 5"]="Panel 5/rf3536k4ka.dtb"
    ["Clone Panel 6"]="Panel 6/rf3536k4ka.dtb"
    ["Clone Panel 7"]="Panel 7/rf3536k4ka.dtb"
    ["Clone Panel 8"]="Panel 8/rf3536k4ka.dtb"
    ["Clone Panel 9"]="Panel 9/rf3536k4ka.dtb"
    ["Clone Panel 10"]="Panel 10/rf3536k3ka.dtb"
    ["R36 Max"]="R36 Max/rf3536k4ka.dtb"
    ["RX6S"]="RX6S/rf351g3ka.dtb"
)

# Clone panel timings (extracted from decompiled DTBs)
declare -A CLONE_CLOCK=(
    ["Clone Panel 1"]=30000000   ["Clone Panel 2"]=30000000
    ["Clone Panel 3"]=30000000   ["Clone Panel 4"]=30000000
    ["Clone Panel 5"]=30000000   ["Clone Panel 6"]=30000000
    ["Clone Panel 7"]=30000000   ["Clone Panel 8"]=30000000
    ["Clone Panel 9"]=30000000   ["Clone Panel 10"]=30000000
    ["R36 Max"]=50000000         ["RX6S"]=30000000
)
declare -A CLONE_HACTIVE=(
    ["Clone Panel 1"]=640  ["Clone Panel 2"]=640  ["Clone Panel 3"]=640
    ["Clone Panel 4"]=640  ["Clone Panel 5"]=640  ["Clone Panel 6"]=640
    ["Clone Panel 7"]=640  ["Clone Panel 8"]=640  ["Clone Panel 9"]=640
    ["Clone Panel 10"]=640 ["R36 Max"]=720        ["RX6S"]=640
)
declare -A CLONE_VACTIVE=(
    ["Clone Panel 1"]=480  ["Clone Panel 2"]=480  ["Clone Panel 3"]=480
    ["Clone Panel 4"]=480  ["Clone Panel 5"]=480  ["Clone Panel 6"]=480
    ["Clone Panel 7"]=480  ["Clone Panel 8"]=480  ["Clone Panel 9"]=480
    ["Clone Panel 10"]=480 ["R36 Max"]=720        ["RX6S"]=480
)
declare -A CLONE_HFP=(
    ["Clone Panel 1"]=150  ["Clone Panel 2"]=150  ["Clone Panel 3"]=46
    ["Clone Panel 4"]=46   ["Clone Panel 5"]=150  ["Clone Panel 6"]=46
    ["Clone Panel 7"]=188  ["Clone Panel 8"]=150  ["Clone Panel 9"]=46
    ["Clone Panel 10"]=120 ["R36 Max"]=140        ["RX6S"]=46
)
declare -A CLONE_HSYNC=(
    ["Clone Panel 1"]=50   ["Clone Panel 2"]=50   ["Clone Panel 3"]=2
    ["Clone Panel 4"]=2    ["Clone Panel 5"]=50   ["Clone Panel 6"]=2
    ["Clone Panel 7"]=20   ["Clone Panel 8"]=50   ["Clone Panel 9"]=2
    ["Clone Panel 10"]=120 ["R36 Max"]=80         ["RX6S"]=2
)
declare -A CLONE_HBP=(
    ["Clone Panel 1"]=150  ["Clone Panel 2"]=150  ["Clone Panel 3"]=44
    ["Clone Panel 4"]=44   ["Clone Panel 5"]=150  ["Clone Panel 6"]=44
    ["Clone Panel 7"]=186  ["Clone Panel 8"]=150  ["Clone Panel 9"]=44
    ["Clone Panel 10"]=120 ["R36 Max"]=140        ["RX6S"]=44
)
declare -A CLONE_VFP=(
    ["Clone Panel 1"]=20   ["Clone Panel 2"]=20   ["Clone Panel 3"]=16
    ["Clone Panel 4"]=16   ["Clone Panel 5"]=20   ["Clone Panel 6"]=16
    ["Clone Panel 7"]=11   ["Clone Panel 8"]=20   ["Clone Panel 9"]=16
    ["Clone Panel 10"]=16  ["R36 Max"]=20         ["RX6S"]=16
)
declare -A CLONE_VSYNC=(
    ["Clone Panel 1"]=6    ["Clone Panel 2"]=6    ["Clone Panel 3"]=2
    ["Clone Panel 4"]=2    ["Clone Panel 5"]=6    ["Clone Panel 6"]=2
    ["Clone Panel 7"]=2    ["Clone Panel 8"]=6    ["Clone Panel 9"]=2
    ["Clone Panel 10"]=4   ["R36 Max"]=4          ["RX6S"]=2
)
declare -A CLONE_VBP=(
    ["Clone Panel 1"]=12   ["Clone Panel 2"]=12   ["Clone Panel 3"]=14
    ["Clone Panel 4"]=14   ["Clone Panel 5"]=12   ["Clone Panel 6"]=14
    ["Clone Panel 7"]=8    ["Clone Panel 8"]=12   ["Clone Panel 9"]=14
    ["Clone Panel 10"]=12  ["R36 Max"]=20         ["RX6S"]=14
)

# All clones: pixclk=0, delays=20/20/120, dimensions=153x85
CLONE_PIXCLK=0
CLONE_PREPARE_DELAY=20
CLONE_RESET_DELAY=20
CLONE_ENABLE_DELAY=120
CLONE_WIDTH=153
CLONE_HEIGHT=85

#------------------------------------------------------------------------------
# Extract panel-init-sequence from compiled DTB (clone panels)
#------------------------------------------------------------------------------
extract_init_from_dtb() {
    local dtb_file="$1"

    if [ ! -f "$dtb_file" ]; then
        echo ""
        return
    fi

    # Decompile DTB and extract init-sequence using python for reliable parsing
    # (bash grep/sed has locale issues with binary content in decompiled DTBs)
    python3 -c "
import subprocess, re, sys
r = subprocess.run(['dtc', '-I', 'dtb', '-O', 'dts', '$dtb_file'],
                   capture_output=True, text=True, timeout=10)
for line in r.stdout.split('\n'):
    if 'panel-init-sequence' in line:
        m = re.search(r'\[([^\]]+)\]', line)
        if m:
            print(m.group(1).strip())
            sys.exit(0)
" 2>/dev/null
}

#------------------------------------------------------------------------------
# Generate .dtso overlay for a clone panel
#------------------------------------------------------------------------------
generate_clone_dtso() {
    local panel_name="$1"
    local init_seq="$2"
    local safe_name
    safe_name=$(echo "$panel_name" | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
    local dtso_file="$OUTPUT_DIR/${safe_name}.dtso"

    local clock="${CLONE_CLOCK[$panel_name]}"
    local hactive="${CLONE_HACTIVE[$panel_name]}"
    local vactive="${CLONE_VACTIVE[$panel_name]}"
    local hfp="${CLONE_HFP[$panel_name]}"
    local hsync="${CLONE_HSYNC[$panel_name]}"
    local hbp="${CLONE_HBP[$panel_name]}"
    local vfp="${CLONE_VFP[$panel_name]}"
    local vsync="${CLONE_VSYNC[$panel_name]}"
    local vbp="${CLONE_VBP[$panel_name]}"

    cat > "$dtso_file" << DTSO_EOF
/dts-v1/;
/plugin/;

/* Arch R - ${panel_name} MIPI DSI Overlay */
/* Auto-generated by generate-panel-dtbos.sh */

/ {
	fragment@0 {
		target-path = "${PANEL_PATH}";
		__overlay__ {
			prepare-delay-ms = <${CLONE_PREPARE_DELAY}>;
			reset-delay-ms = <${CLONE_RESET_DELAY}>;
			init-delay-ms = <20>;
			enable-delay-ms = <${CLONE_ENABLE_DELAY}>;
			disable-delay-ms = <20>;
			unprepare-delay-ms = <20>;
			width-mm = <${CLONE_WIDTH}>;
			height-mm = <${CLONE_HEIGHT}>;

			panel-init-sequence = [
				${init_seq}
			];

			panel-exit-sequence = [
				05 14 01 28
				05 0a 01 10
			];
		};
	};

	fragment@1 {
		target-path = "${TIMING_PATH}";
		__overlay__ {
			clock-frequency = <${clock}>;
			hactive = <${hactive}>;
			vactive = <${vactive}>;
			hfront-porch = <${hfp}>;
			hsync-len = <${hsync}>;
			hback-porch = <${hbp}>;
			vfront-porch = <${vfp}>;
			vsync-len = <${vsync}>;
			vback-porch = <${vbp}>;
			hsync-active = <0>;
			vsync-active = <0>;
			de-active = <0>;
			pixelclk-active = <${CLONE_PIXCLK}>;
		};
	};
};
DTSO_EOF

    echo "$dtso_file"
}

#------------------------------------------------------------------------------
# Generate Clone Panel DTBOs
#------------------------------------------------------------------------------
log ""
log "=== Generating Clone Panel DTBO Overlays ==="
log "Source: $CLONES_DIR"
log ""

CLONE_ORDER=("Clone Panel 1" "Clone Panel 2" "Clone Panel 3" "Clone Panel 4" \
             "Clone Panel 5" "Clone Panel 6" "Clone Panel 7" "Clone Panel 8" \
             "Clone Panel 9" "Clone Panel 10" "R36 Max" "RX6S")

for panel_name in "${CLONE_ORDER[@]}"; do
    dtb_file="$CLONES_DIR/${CLONE_DTB[$panel_name]}"
    log "${panel_name}: ${CLONE_DTB[$panel_name]}"

    # Extract init sequence from compiled DTB
    init_seq=$(extract_init_from_dtb "$dtb_file")
    if [ -z "$init_seq" ]; then
        warn "  Could not extract init-sequence from $dtb_file"
        FAILED=$((FAILED + 1))
        continue
    fi

    seq_bytes=$(echo "$init_seq" | wc -w)
    log "  Init sequence: ${seq_bytes} bytes"
    log "  Clock: ${CLONE_CLOCK[$panel_name]} Hz, ${CLONE_HACTIVE[$panel_name]}x${CLONE_VACTIVE[$panel_name]}"
    log "  Timings: ${CLONE_HFP[$panel_name]}/${CLONE_HSYNC[$panel_name]}/${CLONE_HBP[$panel_name]} ${CLONE_VFP[$panel_name]}/${CLONE_VSYNC[$panel_name]}/${CLONE_VBP[$panel_name]}"

    # Generate .dtso
    dtso_file=$(generate_clone_dtso "$panel_name" "$init_seq")

    # Compile to .dtbo
    safe_name=$(echo "$panel_name" | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
    dtbo_file="$OUTPUT_DIR/${safe_name}.dtbo"
    if dtc -I dts -O dtb -@ -o "$dtbo_file" "$dtso_file" 2>/dev/null; then
        dtbo_size=$(stat -c%s "$dtbo_file")
        log "  Compiled: ${safe_name}.dtbo (${dtbo_size} bytes)"
        GENERATED=$((GENERATED + 1))
    else
        warn "  Failed to compile ${safe_name}.dtso"
        FAILED=$((FAILED + 1))
    fi
done

#------------------------------------------------------------------------------
# Pre-merge DTBs (overlay applied at build-time, not boot-time)
#
# This eliminates U-Boot's fdt apply at boot, which has known bugs in BSP
# U-Boot (property replacement with different-sized data can corrupt the DTB).
# Instead, fdtoverlay runs on the build host where it's verified to work.
#------------------------------------------------------------------------------
log ""
log "=== Pre-merging Panel DTBs ==="

MERGED_DIR="$OUTPUT_DIR/merged"
rm -rf "$MERGED_DIR"
mkdir -p "$MERGED_DIR"

# Check for fdtoverlay
if ! command -v fdtoverlay &>/dev/null; then
    error "fdtoverlay not found. Install with: sudo apt install device-tree-compiler"
fi

# Determine base DTBs (passed via --base-dtb-original and --base-dtb-clone, or auto-detect)
BASE_DTB_ORIGINAL="${BASE_DTB_ORIGINAL:-$PROJECT_DIR/output/boot/rk3326-gameconsole-r36s.dtb}"
BASE_DTB_CLONE="${BASE_DTB_CLONE:-$PROJECT_DIR/output/boot/rk3326-gameconsole-r36s-clone-type5.dtb}"

MERGED_COUNT=0

# R36S original panels (Panel 0-5)
if [ -f "$BASE_DTB_ORIGINAL" ]; then
    log "Base DTB (original): $BASE_DTB_ORIGINAL"
    for panel_num in 0 1 2 3 4 5; do
        dtbo_file="$OUTPUT_DIR/panel${panel_num}.dtbo"
        merged_file="$MERGED_DIR/kernel-panel${panel_num}.dtb"
        if [ -f "$dtbo_file" ]; then
            if fdtoverlay -i "$BASE_DTB_ORIGINAL" -o "$merged_file" "$dtbo_file" 2>/dev/null; then
                log "  kernel-panel${panel_num}.dtb ($(stat -c%s "$merged_file") bytes)"
                MERGED_COUNT=$((MERGED_COUNT + 1))
            else
                warn "  Failed to merge panel${panel_num}.dtbo"
            fi
        fi
    done
else
    warn "Base DTB (original) not found: $BASE_DTB_ORIGINAL"
fi

# Clone panels
if [ -f "$BASE_DTB_CLONE" ]; then
    log "Base DTB (clone): $BASE_DTB_CLONE"

    # Map: panel_name -> merged DTB filename
    declare -A CLONE_MERGED_NAME=(
        ["Clone Panel 1"]="kernel-clone1.dtb"
        ["Clone Panel 2"]="kernel-clone2.dtb"
        ["Clone Panel 3"]="kernel-clone3.dtb"
        ["Clone Panel 4"]="kernel-clone4.dtb"
        ["Clone Panel 5"]="kernel-clone5.dtb"
        ["Clone Panel 6"]="kernel-clone6.dtb"
        ["Clone Panel 7"]="kernel-clone7.dtb"
        ["Clone Panel 8"]="kernel-clone8.dtb"
        ["Clone Panel 9"]="kernel-clone9.dtb"
        ["Clone Panel 10"]="kernel-clone10.dtb"
        ["R36 Max"]="kernel-r36max.dtb"
        ["RX6S"]="kernel-rx6s.dtb"
    )

    for panel_name in "${CLONE_ORDER[@]}"; do
        safe_name=$(echo "$panel_name" | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
        dtbo_file="$OUTPUT_DIR/${safe_name}.dtbo"
        merged_name="${CLONE_MERGED_NAME[$panel_name]}"
        merged_file="$MERGED_DIR/$merged_name"
        if [ -f "$dtbo_file" ]; then
            if fdtoverlay -i "$BASE_DTB_CLONE" -o "$merged_file" "$dtbo_file" 2>/dev/null; then
                log "  $merged_name ($(stat -c%s "$merged_file") bytes)"
                MERGED_COUNT=$((MERGED_COUNT + 1))
            else
                warn "  Failed to merge ${safe_name}.dtbo"
            fi
        fi
    done
else
    warn "Base DTB (clone) not found: $BASE_DTB_CLONE"
fi

#------------------------------------------------------------------------------
# Summary
#------------------------------------------------------------------------------
log ""
log "=== Panel Generation Complete ==="
log "DTBOs generated: ${GENERATED}"
log "Pre-merged DTBs: ${MERGED_COUNT}"
[ $FAILED -gt 0 ] && warn "Failed: ${FAILED}"
log ""
log "Output: $MERGED_DIR/"
ls -1 "$MERGED_DIR"/*.dtb 2>/dev/null | while read f; do
    log "  $(basename "$f")"
done
log ""
log "These pre-merged DTBs go on BOOT partition. boot.ini loads the selected one."
